import type { Classification,Contact } from '../types';
const FREE=new Set(['gmail.com','yahoo.com','outlook.com','hotmail.com','icloud.com','aol.com']);
const GENERIC=/^(program|residency|fellowship|education|coordinator|office|info|contact|training|meded)[._-]?/i;
export const normalizeEmail=(email:string)=>email.trim().toLowerCase().replace(/^mailto:/,'').split('?')[0];
export const isValidEmail=(email:string)=>/^[a-z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)+$/i.test(normalizeEmail(email));
export const classifyEmail=(email:string):Classification=>{const n=normalizeEmail(email);if(!isValidEmail(n))return'Invalid email';const [local,domain]=n.split('@');if(FREE.has(domain))return'Free-email address requiring review';if(GENERIC.test(local))return'Generic program contact';return'Institutional professional email'};
export interface ExtractedEmail {email:string;evidence:string}
export function extractEmails(html:string):ExtractedEmail[]{const doc=new DOMParser().parseFromString(html,'text/html');doc.querySelectorAll('script,style,noscript,nav,footer,aside,[hidden],[aria-hidden="true"]').forEach(e=>e.remove());const found=new Map<string,string>();doc.querySelectorAll('a[href^="mailto:" i]').forEach(a=>{const email=normalizeEmail(a.getAttribute('href')||'');if(isValidEmail(email))found.set(email,(a.parentElement?.textContent||a.textContent||'').replace(/\s+/g,' ').trim().slice(0,240))});if(doc.body){const walker=doc.createTreeWalker(doc.body,NodeFilter.SHOW_TEXT);let node:Node|null;while((node=walker.nextNode())){const text=node.textContent||'';for(const match of text.matchAll(/[A-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)){const email=normalizeEmail(match[0]);const context=node.parentElement?.textContent||text;found.set(email,context.replace(/\s+/g,' ').trim().slice(0,240))}}}return [...found].map(([email,evidence])=>({email,evidence}))}
export function deduplicateContacts(records:Contact[]):Contact[]{const map=new Map<string,Contact>();for(const r of records){const key=normalizeEmail(r.professional_email),urls=[...(r.source_urls||[]),r.source_url].filter(Boolean);const prior=map.get(key);if(prior)map.set(key,{...prior,source_urls:[...new Set([...prior.source_urls,...urls])],email_classification:'Duplicate'});else map.set(key,{...r,professional_email:key,source_urls:[...new Set(urls)]})}return [...map.values()]}
