import type { Classification,Contact } from '../types';
const FREE=new Set(['gmail.com','yahoo.com','outlook.com','hotmail.com','icloud.com','aol.com']);
const GENERIC=/^(program|residency|fellowship|education|coordinator|office|info|contact|training|meded)[._-]?/i;
export const normalizeEmail=(email:string)=>email.trim().toLowerCase().replace(/^mailto:/,'').split('?')[0];
export const isValidEmail=(email:string)=>/^[a-z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)+$/i.test(normalizeEmail(email));
export const classifyEmail=(email:string):Classification=>{const n=normalizeEmail(email);if(!isValidEmail(n))return'Invalid email';const [local,domain]=n.split('@');if(FREE.has(domain))return'Free-email address requiring review';if(GENERIC.test(local))return'Generic program contact';return'Institutional professional email'};
export interface ExtractedEmail {email:string;evidence:string}
export function extractEmails(html:string):ExtractedEmail[]{const doc=new DOMParser().parseFromString(html,'text/html');doc.querySelectorAll('script,style,noscript,nav,footer,aside,[aria-hidden="true"]').forEach(e=>e.remove());const found=new Map<string,string>();doc.querySelectorAll('a[href^="mailto:"]').forEach(a=>{const email=normalizeEmail(a.getAttribute('href')||'');if(isValidEmail(email))found.set(email,(a.parentElement?.textContent||a.textContent||'').trim().slice(0,240))});const text=doc.body?.textContent||'';for(const match of text.matchAll(/[A-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)){const email=normalizeEmail(match[0]);const start=Math.max(0,(match.index||0)-90);found.set(email,text.slice(start,start+email.length+180).replace(/\s+/g,' ').trim())}return [...found].map(([email,evidence])=>({email,evidence}))}
export function deduplicateContacts(records:Contact[]):Contact[]{const map=new Map<string,Contact>();for(const r of records){const key=normalizeEmail(r.professional_email);const prior=map.get(key);if(prior){prior.source_urls=[...new Set([...prior.source_urls,...r.source_urls,r.source_url])];prior.email_classification='Duplicate'}else map.set(key,{...r,professional_email:key,source_urls:[...new Set([...(r.source_urls||[]),r.source_url])]})}return [...map.values()]}
